feat: add bcrypt to hashing and validate password
KTPM-Techxi/techxi-backend pull request #5
Opened 2023-07-15 15:38 UTC by heomeco2014

## Code

- [ ] Thêm API nào?
    - ** List here
- [ ] Có migration không?
    - ** List here tables
- [] Có hơn 300 line code?

## Testing

- [ ] Đã test ở local?

## Document

- [ ] Có document không?
- Link: 

## Noted
- **Nhớ update ticket nhé! :D

2023-07-15 15:39 UTC, heomeco2014 reviewed
Review nhớ đọc comment nhá

2023-07-15 17:18 UTC, ducanng requested changes
=)) giúp anh Minh 1 tí trên con đường fullstack!

2023-07-15 17:18 UTC, ducanng commented on controller/User/login.controller.js
>    const { email, password } = req.body;
mặc dù là login cần check valid request luôn nhé. ở đây maybe có thể chỉ cần xử lý empty value thôi bên phía frontend xử lí format, ...

2023-07-15 17:18 UTC, ducanng commented on controller/User/login.controller.js
> +    const user = await User.findOne({ email });
.
└── routes/
........├── auth.js // nếu dùng chung thì để thế này
........├── callcenter/
.........|── customer/
........└── driver/
└── controller/
.........├── user/
.........│.........├──login.controller.js
.........│.........├──egister.controller.js
.........│.........└──type.js // define request and response
└── internal/
.........├── service/
.........│.........├──user/
.........│.........├──user.service.js
.........│.........└──user.dto.js  // Data transfer object
.........├── model/
.........│.........├── user.dm.js
.........│.........└──const.js
.........└── repository/
.........│.........└──user.repository.js

Cấu trúc sẽ là thế này! Controller sẽ call service. Service kiểm tra logic, gọi repo để lấy data, ... hay làm thêm gì đó v.v Ex: lấy data, xử lý logic, hash password trả dữ liệu ra cho controller để đưa result user
Controller chỉ là nơi để giao tiếp với user nên là ko nên để logic mà chỉ được non-logic thôi nhé. 
Mỗi function từ service đổ đi trả về thêm error để mình có thể dễ dàng handle được. Chỗ nào handle error thì log hết ra nhóe!

2023-07-15 17:18 UTC, ducanng commented on controller/User/login.controller.js
> +      return res.status(400).json({ message: 'Invalid email or password' });
cái này thì nó lặp lại nhiều nên làm function trả về respone with status code. 
folder common/httputil

còn error message có thể định nghĩa những cái chung chung ở common/errorutil

2023-07-15 17:18 UTC, ducanng commented on controller/User/login.controller.js
> +      return res.status(200).json({ message: 'Login successful' });
Mấy cái tương tự thì nhớ tự biết làm ở đâu handle hêt nha

2023-07-15 17:18 UTC, ducanng commented on models/User.js
>  const UserSchema = new Schema({
Schema table có sửa đổi chút đỉnh về [design](/https://dbdiagram.io/d/649481fb02bd1c4a5eebc9e4) 
Anh xem migrate luôn cho cả driver, customer, call center agents.

2023-07-15 17:18 UTC, ducanng commented on services/bcrypt.service.js
cái này ok nè =)) tương lai có thể mở rộng thêm function hash nhiều thứ khác! =))

2023-07-16 06:11 UTC, ducanng commented on models/Role.js
làm chi thừa vậy

2023-07-16 06:12 UTC, ducanng commented on app/config/auth.config.js
> +  secret: 'nhatminhdepzaivaicaloz'
=))

2023-07-16 06:17 UTC, ducanng commented on app.js
> +function initial() {
function này để làm gì? count lấy từ đâu?

2023-07-16 06:22 UTC, ducanng commented on controller/User/login.controller.js
thư mục này nên đổi thành auth vì dùng để xác định danh tính người dùng chứ không phải là features dành cho user

2023-07-16 06:27 UTC, ducanng commented on middlewares/authJwt.js
> +isDriver = (req, res, next) => {
nó như nhau sao không làm 1 func để check role thôi

2023-07-16 06:28 UTC, ducanng commented on models/Role.js
không phải tạo file riêng thế này để trong user là được rồi.

2023-07-16 06:30 UTC, ducanng commented on models/User.js
> +  roles: [
mongoose có hỗ trợ enum. Code mới nhất của em có làm model user_credentials. DB có thay đổi 1 xíu

2023-07-16 06:33 UTC, ducanng commented on routes/users.js
> +const logOutController = require('../controller/User/logout.controller');
=)) chữ O to thế

2023-07-16 17:15 UTC, heomeco2014 commented on app.js
> +function initial() {
để chia role thôi, tại làm theo người ta chia ra làm 3 role

2023-07-28 19:51 UTC, ducanng requested changes

2023-07-28 19:51 UTC, ducanng commented on app.js
> +function initial() {
rắc rối thế. Define constant là lưu ở user là được rồi

2023-07-28 19:51 UTC, ducanng commented on app/config/auth.config.js
remove

2023-07-28 19:51 UTC, ducanng commented on controller/authcontroller/auth.controller.js
> +    const user = req.body;
anh phải check đầu vào chứ ở đây != rỗng là được rồi

2023-07-28 19:51 UTC, ducanng commented on controller/authcontroller/auth.controller.js
> +        return res.cookie("token", token, { httpOnly: true }).json(newUser);
actually thì đăng ký trả ra id là được rồi sau đó đến trang detail hoặc làm gì đó khác dựa vào id user đã lấy ra đc

2023-07-28 19:51 UTC, ducanng commented on internal/repository/user.repo.js
> +        const user = await User.findOne({ email: email });
cái này do anh ko check input =)) ở register đó

2023-07-28 19:51 UTC, ducanng commented on internal/repository/user.repo.js
> +        const user = await User.findOne({ email: email });
@heomeco2014

2023-07-28 19:51 UTC, ducanng commented on internal/service/userservice/user.service.js
> +        const newUser = await User.create({ email, phoneNumber, name, password: hashedPassword });
như trên =))

2023-07-28 19:51 UTC, ducanng commented on internal/service/userservice/user.service.js
> +        const newUser = await User.create({ email, phoneNumber, name, password: hashedPassword });
cái này phải nằm ở repo chứ :) đây là tầng service mà

2023-07-29 15:32 UTC, heomeco2014 commented on app/config/auth.config.js
Để đó đi cứ từ từ, cái này làm theo tutorial, để đó mốt còn biết t làm theo tutorial nào :)))

2023-07-29 15:39 UTC, heomeco2014 commented on internal/repository/user.repo.js
> +        const user = await User.findOne({ email: email });
thật ra bên FE t validate bằng lib luôn rồi =)) Vô đây validate lại lần nữa hả

2023-07-29 16:12 UTC, ducanng commented on internal/repository/user.repo.js
> +        const user = await User.findOne({ email: email });
có chứ bên kia lỡ như cái lib nó bị lỗi thì sao anh?
 phải valid ở backend nữa chứ thường thì chỉ check xem nó có != empty value không hay thôi vì empty value thường hay bị lỗi crash app hoặc dễ bị tấn công sql injection.

2023-07-30 15:41 UTC, ducanng approved these changes

2023-07-30 15:42 UTC, merged